### ISSUE TITLE
Washingtonpost.com Detects Still

### ISSUE THREAD

**Issue by thefinalcrisis** [hensm/hide_private_mode#2]
Thanks for making this extension, it's really useful! Just wanted to report that Washington Post seems to have found a way to block this extension. Is there any way to update it as a workaround?

![image](https://user-images.githubusercontent.com/57545985/68513475-1bc53a80-0249-11ea-9469-6a3c225d00ac.png)

**Comment by skidunion** [comment]
Nano / UBO filter: `washingtonpost.com##^script:has-text(adblocker-detected)`

**Comment by hensm** [comment]
Missed this, sorry.

WaPo doesn't seem to detect private browsing via indexedDB (or it doesn't call it at least). Will have to investigate.

**Comment by hensm** [comment]
`navigator.serviceWorker` is apparently undefined in private mode. Added a quick fix to set it to a blank object instead, but should be fine for now.

**Comment by duncreg** [comment]
In my experience, it's not working; experienced this on both Linux and Windows.

[Example of not working](https://imgur.com/eUOC8VV)
[Run in private mode is enabled](https://imgur.com/RNTfWMl)

**Comment by hensm** [comment]
@duncreg That’s working fine. Tracking protection is blocking ads and causing that.
