### ISSUE TITLE
Breaks Twitter and Instagram

### ISSUE THREAD

**Issue by bpmackow** [hensm/hide_private_mode#3]
This extension causes permalinks to tweets and Instagram posts to not load properly in private browsing. Instagram displays a nearly blank page, while Twitter does not load links (including link preview cards and links to bigger versions of images). I'm sure it's this extension because after disabling it and performing a hard refresh, the pages load normally.

Example screenshots:
![Instagram post loading only a white background & logo](https://user-images.githubusercontent.com/40656934/70934641-911bec00-1ffb-11ea-99aa-bb726e01c0ad.png)

![Tweet with blank spot where link card should be](https://user-images.githubusercontent.com/40656934/70934772-ea841b00-1ffb-11ea-9d6c-b341be21adf3.png)

**Comment by hensm** [comment]
524b782 ⁠— Fixed (#4)

**Comment by snowice0** [comment]
I actually am getting a similar error on version 0.0.4. Twitter does not load new content ie: the home is 3 tweets without preview and scrolling down leads to an infinite loading loops, which is the same for any other page except with more tweets. Using the search bar doesn't live populate with suggestions/recommendations as it would before

**Comment by hensm** [comment]
New or old twitter? Got any errors in the web console?

**Comment by snowice0** [comment]
good point, I am actually using the old twitter layout by Wolvan. There are a few Source map errors with JS 404ing and TypeError: navigator.serviceWorker.addEventListener . . .

**Comment by hensm** [comment]
Oh right, it’s an event target, missed that. Should be an easy fix, will push an update later.

**Comment by snowice0** [comment]
great, thanks!
