### ISSUE TITLE
TypeError: navigator.serviceWorker.getRegistrations is not a function

### ISSUE THREAD

**Issue by cbrown350** [hensm/hide_private_mode#4]
`navigator.serviceWorker` is apparently undefined in private mode. Added a quick fix to set it to a blank object instead, but should be fine for now.

_Originally posted by @hensm in https://github.com/hensm/hide_private_mode/issues/2#issuecomment-561854514_

Looks like, possibly related to the closed issue, there's still an issue with the serviceWorker object when the extension is enabled. It breaks a lot of forums, such as https://forums.insynchq.com and https://forum.manjaro.org. They stop loading, resulting in a blank page.

Console shows an error in the JavaScript: TypeError: navigator.serviceWorker.getRegistrations is not a function

The error isn't there when the extension is disabled. (I'm on an Ubuntu variant of Linux)

**Comment by hensm** [comment]
I’m guessing they do feature detection and this breaks that because it doesn’t provide any properties. Might be able to just stub them, will check it out when I’m back home.

**Comment by hensm** [comment]
524b782 ⁠— Fixed
